### ISSUE TITLE
たつろお予測コードつくって

### ISSUE THREAD

**Issue by nami73b** [nami73b/boat_race_ai#17]
input
ローカルのcsv
output
gcsの`boat_race_ai/results/{date}/{place_id}/{race_number}/prediction_result.csv`

**Comment by nami73b** [comment]
予測結果はGCSにはいて
パス: prediction_result/{日付 YYYYMMDD}/{place_id}_{race_no}_prediction_result.csv

参考コード
```
self.bucket.upload_csv_from_string(
    <<<予測結果のDataFrame>>>.to_csv(encoding="utf-8", index=False),
     <<<パス>>>
          )
      ) 
```

**Comment by nami73b** [comment]
dataframeのカラム
race_date, place_id, race_no, bracket_no, bet_type, probability

bet_typeはとりあえず1を固定で入れといて

**Comment by tai72** [comment]
・予測コードの修正
・GCS に予測結果を吐き出すコードの追加
これらの変更についてPRしたお
